server:
  port: 8080
spring:
  application:
    name: userService
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
mybatis:
  typeAliasesPackage: com.wei.user.model
  mapperLocations: classpath:mapper/*Mapper.xml