eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: zuulService
zuul:
  routes:
    user:
      path: /user/**
      serviceId: userService #\u5FAE\u670D\u52A1\u540D\u79F0\uFF0C\u7F51\u5173\u4F1A\u4ECEeureka\u4E2D\u83B7\u53D6\u8BE5\u670D\u52A1\u540D\u79F0\u4E0B\u7684\u670D\u52A1\u5B9E\u4F8B\u7684\u5730\u5740
