server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/weiweiweiwei/config_server/
          #username:
          #password:
          search-paths: shopConfig
  application:
    name: configService


