server:
  port: 8089
spring:
  application:
    name: redisService
  redis:
    database: 0
    host: 192.168.1.155
    password: search@redis2019
    timeout: 3000
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
